### ISSUE TITLE
Two repositories?

### ISSUE THREAD

**Issue by dtcallcock** [quartiq/thermostat#2]
Is this repository or the one on fake GitHub at https://git.m-labs.hk/M-Labs/thermostat the one we should submit issues/PRs etc. to?

**Comment by jordens** [comment]
The other one.

**Comment by dtcallcock** [comment]
I'm sure the M-Labs thing is great for backend stuff like your build server and the NIX stuff, but I wish all the more community-facing/involved projects could consistently stay on GitHub.  I mean, is there a reason Stabilizer is on GitHub but this is not (or at least sort of not)?

**Comment by jordens** [comment]
Github is a platform I'm very happy with and most other QUARTIQ projects are here. I'm not actively involved in the development at https://git.m-labs.hk/M-Labs/thermostat.
